### ISSUE TITLE
Dynamic DB Schema

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#1]
The database schema may change. Please replace any hardcoded instances of the 'bt_spatial_test' schema with a dynamic variable that the user can defined in the database.ini file, and update the Database and DataTracker classes as needed.

I recommend creating a property to store the schema variable in the Database class that is initialized in Database.get_params() and can be called in the DataTracker class as database_connection.schema. Open to suggestions!

**Comment by AnthonyRodway** [comment]
One of the latest commits adds in two new fields to the database.ini file

schema =
table = 

These need to be filled out for the connection to work now.

**Comment by AnthonyRodway** [comment]
👍 
https://github.com/cat-cfs/twobilliontoolkit/commit/d11e1f2f5c23eee8aebc603df43d1123ebf72e06

https://github.com/cat-cfs/twobilliontoolkit/commit/930058325fcf79cd4b60e864d9ed27dbbfa3ece8
