### ISSUE TITLE
Add project_spatial_id to log files

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#11]
Please add the project_spatial_id to the log files where possible so it can be easily found in the raw_data_tracker via RecordReviser or the gdb

**Comment by AnthonyRodway** [comment]
Changes are contained in this commit: https://github.com/cat-cfs/twobilliontoolkit/commit/2d50f2bd787eadcec49971d2e3e4894e22bba968

Changes:
- There is now a little message after the tag in most of the logs to indicate which project spatial id the error occurred when processing for.

**Comment by nesdolya** [comment]
Tested and functioning (minimal testing completed)
