### ISSUE TITLE
RecordReviser & SpatialTransformer

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#12]
The RecordReviser pops up at the end of the SpatialTransformer run and I edited a project number. The data_tracker was updated, but the output.gdb feature class was not updated on the network. The update occurred on the local gdb instead.

Please update the path passed to RecordReviser at the end of SpatialTransformer to be the network output gdb.

PS. when ran independently RecordReviser works as expected and updates the network output gdb

**Comment by AnthonyRodway** [comment]
Fixes contained in this commit https://github.com/cat-cfs/twobilliontoolkit/commit/7619e29e916a2f794328b1f9174fb7fdfccd13b7

Feel free to close this issue whenever you are testing and can verify that it is complete, no rush :)

**Comment by nesdolya** [comment]
Working wonderfully!
