### ISSUE TITLE
Delete Local GDB

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#19]
Can we please add code to the commands ps1 file that deletes the data stored on the C drive automatically? If the analyst reruns SpatialTransformer at a later time, it will upload all the data in the local GDB to the network GDB. See hypothetical below.

I can see a few possible implementations and would like to get your feedback before implementation please.

1. [good] Delete local as command number 9 - Exit becomes command number 10
2. [more analyst friendly] Delete local is included in the Exit command, but a debug flag is included in the ps1 variables. If debug == True, then Exit does not delete the local data. If debug==False, then Exit does delete the local data.
3. Both 1 and 2 are implemented
4. [i think this is a bad idea lol] local GDB name has timestamp (including the date and UTM time) appended, so the 2nd+ time SpatialTransformer is ran it alway creates a new local GDB, but this might mess with the resume flag

For example, the analyst runs SpatialTransformer, then runs RecordsReviser to fix the missing project numbers which updates the 000_XXX_00_## layers in the GDB. The analyst then fixes a spatial file manually (e.g. renaming the shapefile) and reruns SpatialTransformer. All the 0000_XXX_00_## layers that were removed were re-added to the network GDB b/c we do not want to change the network GDB name.

**Comment by AnthonyRodway** [comment]
Change has been added to this commit https://github.com/cat-cfs/twobilliontoolkit/commit/cd89184152d699cfbf0a0fb32a4e8651ba64de0e

- Removed old unused script (was not as nice and kind of annoying to update alongside the ps1 script)
- Added a clearing functionality into spatial transformer to clear the local dir after the network transferring has completed, if a debug flag is not included in the tool command
- Added a new command into the ps1 script to remove the contents in the local directory manually

**Comment by nesdolya** [comment]
Tested and functioning as expected.
