### ISSUE TITLE
Record Reviser GDB Updates

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#2]
I ran spatial transformer on the data I shared with you earlier, and found that the content of the GDB matched exactly expected project_spatial_id for records in the database version of the raw_data_tracker (i.e. in_raw_gdb == True). 

When I run the records reviser using a script I wrote at the link below, the names of the feature classes in the GDB are not updated to match the new project_spatial_id, but when I manually change the records in the record reviser GUI the feature class name in the GDB does change. 
Please let me know if I am missing a step on my end (in the below script) or if you have any questions.  Perhaps, there is a bug preventing the renaming of the feature classes when called from the script?

\\vic-fas1\projects_a\2BT\02_Tools\spatial_data_processing_workflow\run_record_reviser.py
I coped the call to the records reviser that would be used if the user provided a change_dict.

**Comment by AnthonyRodway** [comment]
Did you pass the gdb path to the update_recods function?
![image](https://github.com/cat-cfs/twobilliontoolkit/assets/69998437/5dd2cb87-a192-4a17-a620-90b0451f7d3e)
also I am not sure if you changed it but gdb still equals 'path/to/gdb'

**Comment by nesdolya** [comment]
Thanks, I did miss that. I'll rerun!

**Comment by nesdolya** [comment]
When I ran RecordsReviser using the --change command, the GDB was not updated to match the change. 0000_XXX_000_04 should be 2022_CAT_025_16 in the GDB (image 2 is the GDB after running the below command). I think line 430 in records_reviser.py should be updated to include the GDB path based on your above comment?

![image](https://github.com/cat-cfs/twobilliontoolkit/assets/17913842/c79740bc-346d-4031-a5a9-571e735a1f66)

![image](https://github.com/cat-cfs/twobilliontoolkit/assets/17913842/5549a6ef-6d79-44d5-87f5-7e5896c0340a)

**Comment by AnthonyRodway** [comment]
yep it definitely should, my bad good catch

**Comment by AnthonyRodway** [comment]
👍 
https://github.com/cat-cfs/twobilliontoolkit/commit/7b3a00389a042b7254b3d931ccf6aab756404125
