### ISSUE TITLE
Batch SiteMapper

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#23]
In (hopefully) many cases there will be an attribute field in the raw spatial layers (e.g. proj_0000_XXX_000_##) that contains values that are an exact match to the Site Name in the database. Please create a tool, or add functionality to the SiteMapper tool, that automatically matches the SiteID to the correct polygon(s) based on the attribute field. 

If we use regex to match the texts, I would prefer if the user could see the matching before they submit the changes to the database. If we look for exact matches, then perhaps we don't need to. Let's discuss. 

User input: 
- the field name in the raw data layer/feature class that contains the Site Name values
- [possibly] the path to the raw data layer/feature class
- overwrite option (same functionality as SiteMapper)

**Comment by AnthonyRodway** [comment]
Initial change contained in this commit: https://github.com/cat-cfs/twobilliontoolkit/commit/88d049e98ba42121f9dd2f6745f24c34d2f0c4a7

This is on the Batch-SiteMapper branch.

Changes:
- a link below the site mapper is added to the tool list dockpane view. This will load up an extra module in the site mapper view 
- The new module is for the user to try and match (select) the features within the layer that correspond to the filtered site name 
- Hopefully this makes things a bit easier but testing will truly tell

Also, the way the entries are matched in this commit is not the greatest, so a commit early next week after a disscusion will be more robust and work better.

**Comment by AnthonyRodway** [comment]
More advanced regex matching / query building changes in this commit: https://github.com/cat-cfs/twobilliontoolkit/commit/dbf1702fc624e15cbafba26ee1dd9434c4d286ac

**Comment by AnthonyRodway** [comment]
Requirements:
- The user will select a project number, a layer (in the drawing order), and a field from the attribute table to match (from the dropdown). After clicking the match button, it will join a site id to every feature it can in the layer (in the bt_site_id column) based on if it can find a suitable match in the site names.
- After the layers are matched to a site id, the user can manually or by a button (possible in future) remove any that may be wrong
- After the checking is complete, the send button will look at the bt_site_id column, the selected project number and the geometries to push into the database.

**Comment by AnthonyRodway** [comment]
New changes of the tool are contained in this commit: https://github.com/cat-cfs/twobilliontoolkit/commit/497f79af2f1f2fb7ee035dbf90e67e1fde8e9950

The tool should now adhere to the above requirements. The only thing that has not been updated (a future thing) would be to match the site name to the row based on a tier system. Right now it just matches to the first site name that it finds whether is be an exact match or around a 75% match

**Comment by AnthonyRodway** [comment]
Branch has been merged to main.
