### ISSUE TITLE
Add 2BT Spatial Data to ArcPro

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#29]
Please create a tool that automatically adds the 2BT spatial datasets to the ArcPro Map with user-friendly names. This way the user does not have to sift through the DB tables to find the correct spatial data. This tool can be created iteratively such that:

1. On button click all 3 dataset are added to the ArcPro map. If possible layer names could be changed from <database>.<schema>.<table name> to more user-friendly names (e.g. 2BT Site Polygons, 2BT Site Points, 2BT Site Buffered Points).
3. On button click/drop-down a panel/popup appears allowing the user to filter the datasets by year and/or project number before adding all 3 datasets to the ArcPro map. Include renaming if possible.
4. On button click/drop-down a panel/popup appears allowing the user to filter the datasets by year and/or project number and user can choose which of the 3 datasets to add to the ArcPro map. That is, the user could choose to just add one or two of the three datasets. Include renaming if possible.

Three datasets to add:
- valid_geometry: which is a view of the site_geometry table. This view only shows the sites that have not been dropped. (see SQL below)
- site_points
- site_buffered_points

I think this would be a good tool to add to the Step 1 button on the twobilliontoolkit pane b/c it requires the user to sign into the DB, but if you think that it would be better suited as a new add-in on the add-in menu bar instead let me know. 

`
CREATE OR REPLACE VIEW bt_test_19dec2023.valid_geometry AS
SELECT sg.id, sg.site_id, st_transform(sg.geom,102001)::geometry('multipolygon',102001) as geom, sg.created_by, sg.created_at, sg.edited_by, sg.edited_at
FROM bt_test_19dec2023.site_geometry sg
WHERE sg.dropped = false;
`

**Comment by AnthonyRodway** [comment]
New tool is contained in this commit: https://github.com/cat-cfs/twobilliontoolkit/commit/c78c1cf057bcaea30bdb5615a867657bde431b7a

Has not been thoroughly tested but most of the functionality is in now.

Changes include:
- a new tool in the step 1 placeholder called Import2BTData (name pending..)
- it will open a new view in the logistics view with three default datalayers to be added to the map from the database (valid_geometries, site_points, site_buffered_points)
- the user can toggle each one on or off to exclude or include it when adding them to the map
- the user can go into the options for each data layer and change selected values that will either affect the sql query built essentially filtering the layers down when they are loaded, or to change their name or object id field
- after the user is done playing around with the data layers they can hit the final button on the bottom and it will add the layers to the current active map.

**Comment by AnthonyRodway** [comment]
Possible additions that were not implemented for simplicities sake is having dropdowns for some of the data layer fields (year, project number, object id column) but they could possible unnecessary. Could possibly use a discussion on this.

**Comment by AnthonyRodway** [comment]
Branch has been merged to main.
