### ISSUE TITLE
Update: Editor Field Names

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#3]
Please update the created by and edited by fields in line 446 of the Processor to be unique to 2BT, such as: 'bt_created_by', 'bt_date_created', 'bt_last_edited_by', 'bt_date_edited'.

We don't know if the raw data will have existing creation and editor fields and we don't want to overwrite those existing fields.

**Comment by AnthonyRodway** [comment]
👍 
https://github.com/cat-cfs/twobilliontoolkit/commit/3ccdb1fbc202f986ef71b766d9f61893cbee22cd
