### ISSUE TITLE
Geopandas not installed with twobilliontoolkit

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#36]
Geopandas is not installed after cloning the repository and running the commands on the Spatial-Transformer-Processor-Logic-Change branch. Does this need manual installation?

https://github.com/cat-cfs/twobilliontoolkit/blob/c97d71018ca74810367038626a15b2a6dab668d0/twobilliontoolkit/SpatialTransformer/Processor.py#L10

**Comment by AnthonyRodway** [comment]
Added to the Commit https://github.com/cat-cfs/twobilliontoolkit/blob/BufferBuilder-Processing-Reported-Points/setup.py on the new BufferBuilder Branch and will be included when merged to main.
