### ISSUE TITLE
Handling Fatal KML errors

### ISSUE THREAD

**Issue by AnthonyRodway** [cat-cfs/twobilliontoolkit#38]
In the new logic for processing the data a fatal error occurred when creating the entry for a KML and it did not give any information on which file the error occurred at. Add that in and any other edge case checks you can think of surrounding KMLs since they are processed a bit differently.

**Comment by AnthonyRodway** [comment]
Changes for this are in the commit: https://github.com/cat-cfs/twobilliontoolkit/commit/ba7bda001e513550a106b2b36c3ce5c4eb7b2e65

Changes:
- added a try except block around the kml entry creation process to give more detailed information in the errors and not be thrown back to spatial transformer and exit the tool. This should be a bit more clear and help the analyst fix any errors easier.

**Comment by nesdolya** [comment]
Reviewed and tested
