### ISSUE TITLE
Handle Pandas Type Errors

### ISSUE THREAD

**Issue by AnthonyRodway** [cat-cfs/twobilliontoolkit#39]
The image below is an example of an error when converting a pandas dataframe to a feature in the raw geodatabase. It is similar to a previous error that was fixed with the Datetime64[ns] type in pandas by converting it to a string.

Try to capture all of the types that could cause issues in a similar way of above.

![image](https://github.com/cat-cfs/twobilliontoolkit/assets/69998437/79761a05-0bf7-4924-afe2-503cbb207b4e)

**Comment by AnthonyRodway** [comment]
Changes for this are in the commit: https://github.com/cat-cfs/twobilliontoolkit/commit/ba7bda001e513550a106b2b36c3ce5c4eb7b2e65

Changes: 
- added a string format conversion for if the dataframe has a 'timestamp' column. Tested on the same file and no error was thrown.

**Comment by nesdolya** [comment]
Reviewed and closed
