### ISSUE TITLE
Warning suppression/changes

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#48]
_Option to suppress Image/PDF warnings_
We weren't supposed to have so many PDFs to process when we first added this warning to the log file. The 2BT data team was supposed to place all the spatial data in a separate location from the PDFs, but this was not the case for this years data. Can we add an option to suppress just the Image/PDF warnings? All other warning should still appear.

_Remove file extension from warnings_
The files extensions listed on this page are not 'unsupported filetype' they are required for a shapefile to function. Please remove these warning from the log file (except for xml files). https://desktop.arcgis.com/en/arcmap/latest/manage-data/shapefiles/shapefile-file-extensions.htm
Additionally, the .qix file extension can also be removed from warnings (it is from the QGIS shapefile creation). And '.shp.xml'

**Comment by AnthonyRodway** [comment]
Changes for this issues have been made in the PR #49
