### ISSUE TITLE
Updates to raw_data_tracker output

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#5]
Please replace the project_path in the raw_data_tracker tables (both Excel and PostgreSQL table you are working in) with the raw_gdb_path. This field will store the absolute path (without mapped letter drives) of the output gdb.

Also, update SpatialTransformer to store the output gdb in this field.
Thanks!

**Comment by AnthonyRodway** [comment]
Fixes contained in this commit https://github.com/cat-cfs/twobilliontoolkit/commit/7619e29e916a2f794328b1f9174fb7fdfccd13b7

Feel free to close this issue whenever you are testing and can verify that it is complete, no rush :)
