### ISSUE TITLE
Logging updates

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#51]
_All Logs:_
It could be useful to add a timestamp for when the program starts running and one for when it is done running. Below is an example of the NIR log files

```
08-27 17:57 root         INFO     NIR support package nir_tools version: 0.7.6
08-27 17:57 root         INFO     Running \\vic-fas1\projects_a\NIR_2025\03_Analysis\01_CBM\02_Production\10_InsectUpdate\01_Scripts\01_setup.py
08-27 17:57 root         INFO     Finished: 01_setup.py
```

_Data Duster specific:_
Please create a log file whenever data duster is ran with a header similar to that used in Spatial Transformer (or the above NIR code). If data duster runs without error it will have the start and end time that the program ran. You may choose to write a statement of success, but that is not necessary when the start and end time are included.

**Comment by nesdolya** [comment]
Additional item: This particular message does not need to be included in the warning logs. It appears when the KML has multiple geometry layers. So 2022_CFP_409_15 is a point and 2022_CFP_409_16 is a polygon. 

`27/09/2024 12:41:24 [WARNING] - Project Spatial ID: 2022_CFP_409_16 - Absolute Path: \\vic-fas1\projects_a\2BT\01_Data\2BT_program_data\2023\RawData\01_Processed_Spatial\GCDocs_Sept202024_DD4\2022-CFP-409-reporting\2022-CFP-409-reporting\2023-CFP-409-MAPS.kml already exists in the data tracker! -  Current Spatial ID: 2022_CFP_409_16 Matching Spatial ID: 2022_CFP_409_15
`
If it is easy enough to ignore the warning when the same KML appears due to the different geometry layers within please do so. If it is not easy/straight forward, we can leave it for now.

**Comment by AnthonyRodway** [comment]
Changes contained in this branch: https://github.com/cat-cfs/twobilliontoolkit/tree/New-Logger

**Comment by nesdolya** [comment]
Tested and functioning.
