### ISSUE TITLE
Independent calls to tools cannot connect to DB

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#54]
When running records reviser independently a fatal error occurs (see below). It seems that the database_config file path is not being passed to the independent tools. Additionally, this error persists when the database.ini file in the local installation of Spatial Transformer is manually updated - it does not appear to be creating the DataTracker class object correctly when the database_config file is not passed. 
![image](https://github.com/user-attachments/assets/3cf2ee36-c4bc-4032-bce6-a7cb4060a344)

**Comment by AnthonyRodway** [comment]
Change is contained in this commit: https://github.com/cat-cfs/twobilliontoolkit/pull/53/commits/1d191be5f82923ec24652099a9cc663a480ddd91
