### ISSUE TITLE
Network GDB location different from output_path

### ISSUE THREAD

**Issue by nesdolya** [cat-cfs/twobilliontoolkit#7]
The output_path for ripple unzipple may be different from the output gdb path. Allow the user to pass the full network GDB path as the gdb variable for SpatialTransformer. Log files and attachment folders should be in the same location as the GDB.

Let me know if you have any questions/comments.

**Comment by AnthonyRodway** [comment]
Fixes contained in this commit https://github.com/cat-cfs/twobilliontoolkit/commit/7619e29e916a2f794328b1f9174fb7fdfccd13b7

Feel free to close this issue whenever you are testing and can verify that it is complete, no rush :)

**Comment by nesdolya** [comment]
Tested 8 May 2024. Working well!
