### ISSUE TITLE
Removing 'dropped' entries from Record Reviser GUI

### ISSUE THREAD

**Issue by AnthonyRodway** [cat-cfs/twobilliontoolkit#8]
The entries that have been dropped do not need to appear in the GUI for the Record Reviser. Those can be skipped over when adding the data.

**Comment by AnthonyRodway** [comment]
Currently all dropped entries are omitted, possibly may want to find a way to keep the most recently changes entry in record reviser to make it more clear.

**Comment by AnthonyRodway** [comment]
[#8607f39 ](https://github.com/cat-cfs/twobilliontoolkit/commit/8607f397ed2f4ebec0b63471190a92f27549ce23)

**Comment by nesdolya** [comment]
Agreed - perhaps when RecordsReviser pops up after SpatialTransformer (automatically) it only shows the records associated with the SpatialTransformer call, or if that is too complex, it could filter the data by records added to raw_data_tracker within the last 24 hours. I can`t recall if you tested applying additional filters to RecordsReviser and what your results were. 
Would we be able to add a filter to RecordsReviser? Let's discuss at our next meeting.

**Comment by nesdolya** [comment]
Tested and working well
